apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    purpose: multi-container-demo
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "3600"]
