apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    componennt: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This is a demo pod to show annotations"
    jenkins: "http://jenkins.roboshop.internal/job/annotations/"
spec:
  containers:
  - name: nginx
    image: nginx