apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: COURSE
        value: "KUBERNETEES"
      - name: AUTHOR
        value: "WILLIAM"
