apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
    app: nginx
spec:
  replicas: 3
  #These are the labels set used to create pod replicas., this should match pod labels
  selector:
    matchLabels:
      purpose: rs-demo
      project: roboshop
      app: nginx
    tier: frontend